<template>
  <div class="mx-auto w-3/4 my-12">
    <swiper class="swiper h-auto" :options="swiperOption" :loop="true">
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles001.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles002.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles003.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles004.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles005.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles006.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles007.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles008.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles009.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles010.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles011.jpg"
          fit="inside"
          height="500"
          class="mx-auto"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles012.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles013.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles014.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles015.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles016.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles017.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles018.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles019.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles020.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles021.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles022.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles023.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles024.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles025.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles026.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles027.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles028.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles029.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <swiper-slide
        ><g-image
          src="../assets/images/carousel/littles/thelittles030.jpg"
          height="500"
          class="mx-auto"
          fit="inside"
        />
      </swiper-slide>
      <div class="swiper-button-prev" slot="button-prev"></div>
      <div class="swiper-button-next" slot="button-next"></div>
    </swiper>
  </div>
</template>

<script>
import { Swiper, SwiperSlide } from "vue-awesome-swiper";
import "swiper/css/swiper.css";

export default {
  name: "swiper-example-navigation",
  title: "Navigation",
  components: {
    Swiper,
    SwiperSlide,
  },
  data() {
    return {
      swiperOption: {
        // loop: true,
        preloadImages: false,
        navigation: {
          nextEl: ".swiper-button-next",
          prevEl: ".swiper-button-prev",
        },
      },
    };
  },
};
</script>

<style lang="scss"></style>
